### ISSUE TITLE
Where are people?

### ISSUE THREAD

**Issue by Keital** [JadeCore/JadeCore#103]
Are we a dead project????

**Comment by wowharley** [comment]
On Skype

**Comment by Keital** [comment]
cooler need a talk with you, contact me via email

**Comment by alexkulya** [comment]
The project is not abandoned. Work will be resumed later. Who I have no time for it.

**Comment by SkyFire** [comment]
👍

**Comment by cooler-SAI** [comment]
hi all! 
it's simple
Bodeguero leaves project and created his own here
https://github.com/NoffearrDeathProjecT
I just can make few fixes for DB, but Better in SAI, so I wanna make playeble wowsource 4.3.4 and originall 5.4.7 playeble, alex too, but noone wanna complete it. Some people ask work in TrinityCore and 5.4.8 ( but there too many work) but we don't have DB skilled people for this. and now I don't have free time for this. My start point was - make PLAYEBLE, may be not 100% blizzlike but it's good.

**Comment by cybrann** [comment]
Exams started on university so for next month I won't have free time to do any kind of fixes here. After exams end, I will start updating core to match trinity core standards for easier coding.

**Comment by Ruundok** [comment]
Hi all!

Please keep this really good project alive. You did a really good job so far! I'm just a user/tester, but I want you to know that yours is by far the best core I've seen around for a long time.

I hope there will be more progress soon :-) 

Best wishes to you (especially for cybrann's exams)!

**Comment by Bodeguero** [comment]
@Ruundok You can test my project too.
https://github.com/NoffearrDeathProjecT :neckbeard:
