### ISSUE TITLE
Help me please, damage, hp of creatures.

### ISSUE THREAD

**Issue by andryus** [JadeCore/JadeCore#106]
## **4.3.4 Cataclysm**

I currently have a problem with life and damage to creatures

http://i.imgur.com/nIUqQ1y.jpg

http://i.imgur.com/oYmLtp0.jpg

http://i.imgur.com/Li9iTVn.jpg

I tried several configurations and the problem persists

Rate.Creature.Normal.Damage          = 1 
Rate.Creature.Elite.Elite.Damage     = 0.2 **I have placed 1**
Rate.Creature.Elite.RARE.Damage      = 0.2 **I have placed 1**
Rate.Creature.Elite.RAREELITE.Damage = 0.2 **I have placed 1**
Rate.Creature.Elite.WORLDBOSS.Damage = 0.2 **I have placed 1**

I wish you could help me

**Comment by sunshitwowsucks** [comment]
What core are you even using?

**Comment by SkyFire** [comment]
It's not jadecore

**Comment by alexkulya** [comment]
At this core, these parameters are set to 1. Use the compiled configuration file.

Close.
