### ISSUE TITLE
where to find full database?

### ISSUE THREAD

**Issue by rec0d** [JadeCore/JadeCore#107]
where can i find 5.4.8 full database?

**Comment by Bodeguero** [comment]
@rec0d in [Releases](https://github.com/JadeCore/JadeCore/releases)

**Comment by rec0d** [comment]
is 247,2 mb the full database?

**Comment by alexkulya** [comment]
Yes.

**Comment by SkyFire** [comment]
http://www.projectskyfire.org/index.php?/files/
