### ISSUE TITLE
mysql error.

### ISSUE THREAD

**Issue by rec0d** [JadeCore/JadeCore#108]
username and password is correct. i used this world: http://www.projectskyfire.org/index.php?/files/

In mysql_stmt_prepare() id: 61, sql: "INSERT INTO creature (guid, id , map, zoneId, areaId, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags, isActive) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'zoneId' in 'field list'
In mysql_stmt_prepare() id: 64, sql: "INSERT INTO gameobject (guid, id, map, zoneId, areaId, spawnMask, phaseMask, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state, isActive) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'zoneId' in 'field list'
In mysql_stmt_prepare() id: 54, sql: "SELECT difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, difficulty_entry_4, difficulty_entry_5, difficulty_entry_6, difficulty_entry_7, difficulty_entry_8, difficulty_entry_9, difficulty_entry_10, difficulty_entry_11, difficulty_entry_12, difficulty_entry_13, difficulty_entry_14, KillCredit1, KillCredit2, modelid1, modelid2, modelid3, modelid4, name, subname, IconName, gossip_menu_id, minlevel, maxlevel, exp, exp_unk, faction_A, faction_H, npcflag, speed_walk, speed_run, scale, rank, mindmg, maxdmg, dmgschool, attackpower, dmg_multiplier, baseattacktime, rangeattacktime, unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_class, trainer_race, minrangedmg, maxrangedmg, rangedattackpower, type, type_flags, type_flags2, lootid, pickpocketloot, skinloot, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType, InhabitType, HoverHeight, Health_mod, Mana_mod, Mana_mod_extra, Armor_mod, RacialLeader, questItem1, questItem2, questItem3, questItem4, questItem5, questItem6, movementId, RegenHealth, mechanic_immune_mask, flags_extra, ScriptName FROM creature_template WHERE entry = ?"
Unknown column 'difficulty_entry_4' in 'field list'
In mysql_stmt_prepare() id: 69, sql: "SELECT id, itemEntry, itemCount, seller, startBid, duration, chance FROM blackmarket_template"
Unknown column 'itemCount' in 'field list'
DatabasePool world2 NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors.
Cannot connect to world database 127.0.0.1;3306;root;root;world2

**Comment by rec0d** [comment]
in authserver

In mysql_stmt_prepare() id: 72, sql: "SELECT c.country FROM ip2nationCountries c, ip2nation i WHERE i.ip < ? AND c.code = i.country ORDER BY i.ip DESC LIMIT 0,1"
Table 'auth.ip2nationCountries' doesn't exist
DatabasePool auth NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors.
Cannot connect to database

**Comment by SkyFire** [comment]
Make sure you are using the correct database. 
http://www.projectskyfire.org/index.php?/files/file/26-jcdb-54808/

**Comment by rec0d** [comment]
Thanks but why does auth crashes? I added base sql

**Comment by SkyFire** [comment]
Look and see if there was an update in the updates folder.

**Comment by rec0d** [comment]
i have added those as well, should i make all update from world up folder too?

**Comment by SkyFire** [comment]
I will fix it today. When I get home.
