### ISSUE TITLE
server is up in console but down on the client.

### ISSUE THREAD

**Issue by rec0d** [JadeCore/JadeCore#110]
http://imgur.com/a/jMFSy

**Comment by rec0d** [comment]
http://emudevs.com/showthread.php/5265-Skyfireemu-5-4-8-Realm-offline?highlight=vitrex

i had this today... :) search...
1. i don't suggest use this sitty core, it misses 98% MOP opcodes even when you cast mount your server will crash... :)
2.Download patched wow.exe from here https://mega.nz/#!81M33LQA
key : !cyBJ83mAJkcwULSSj9GCMGhro7kXTb-HybHeWv9IgSg

credit  Vitrex for sharing
and hellfirewow for made it.

**Comment by SkyFire** [comment]
Please don't link to posts that contain copyrighted downloads. :)
