### ISSUE TITLE
Autoattack Bug - need help

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#17]
We have a problem with Emote Autoattack on Melee Arms. Sometimes player loose battle stance and just stay, then attack and stay again. After battle  if you use items for restore health or mana player just standing and eating. If I use any emote, like /lol - all return to normal.

Looks like we have some problems with Emote Opcodes. Need help here

**Comment by cooler-SAI** [comment]
summoning @Joslyn-Maddie  for help )))

**Comment by Keital** [comment]
@cooler-SAI  The summoned creature id you´ve requested wasn´t found

**Comment by cooler-SAI** [comment]
Still waiting))) if someone else can help - it's welcome here

**Comment by cybrann** [comment]
@cooler-SAI Which one do you need ?

**Comment by cooler-SAI** [comment]
anyone

**Comment by cybrann** [comment]
I'll put priority on low because this is cosmetic only and I'll check tomorrow the opcode handling

**Comment by cooler-SAI** [comment]
@cybrann it's will be nice fix this issue)

**Comment by cooler-SAI** [comment]
@cybrann , any progress here?
