### ISSUE TITLE
Kor'Kron Guards in Orgrimmar without Gossip

### ISSUE THREAD

**Issue by darkmord1991** [JadeCore/JadeCore#24]
http://www.wowhead.com/npc=72501/korkron-guard#comments

I did not found a screenshot/picture of it, but I am sure, that they have gossips like the other guards.

**Comment by eXPeRi91** [comment]
> For every Horde race when you talk to them, they say "Make it quick <Race>, you're kind make me sick."
But, if you are an orc they say "You're not with the revolutionaries, are you?"

http://www.wowhead.com/npc=72501/korkron-guard#comments:id=1947555
