### ISSUE TITLE
We need more people!

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#26]
Guys, we really need more people:
- specially DB Developers
- supporters DB
- Core developers ( for support soon 5.4.8 18414 )

If you wanna help us - post here or open new issue and introduce yourself. Thanks to all.

**Comment by PiskelDEV** [comment]
I'm Interested to join as DB Dev. Where I can find the main DB for this repo ?

**Comment by cooler-SAI** [comment]
@PiskelDEV  add you ? in release section https://github.com/JadeEmu/JadeCore_547/releases/tag/JCDB547.04

**Comment by cooler-SAI** [comment]
@PiskelDEV , join https://github.com/JadeEmu/JadeCore_547/invitations

**Comment by PiskelDEV** [comment]
Thanks for the invitation, do we have something like a IRC channel?

**Comment by cooler-SAI** [comment]
@PiskelDEV , we will later, I can add to to our Skype Channel

**Comment by PiskelDEV** [comment]
I see, I'm currently getting Skype on my Computer. I will add you soon

**Comment by cooler-SAI** [comment]
@PiskelDEV , ok, feel free to add commits here and fix DB - you can make your own TODO plan in TODO list. youstart work - I'll add to official to our community. welcome anyway

**Comment by PiskelDEV** [comment]
Alright, I've added you on Skype.

**Comment by cooler-SAI** [comment]
Also need Testers for mmap system test! check this  https://github.com/JadeEmu/JadeCore_547/tree/mmaps

**Comment by Tithand** [comment]
Hello, i from cuba, I'm Interested to join as DB Dev and Core to, i work in that you need

**Comment by cooler-SAI** [comment]
@Tithand , welcome https://github.com/JadeEmu/JadeCore_547/invitations

**Comment by Tithand** [comment]
Thanks for the invitation

**Comment by Tithand** [comment]
cooler-SAI can you give me a link to download the last version of Truice an SAI editor? i have older version and give some errors

**Comment by cooler-SAI** [comment]
Ok, wait

**Comment by cooler-SAI** [comment]
@Tithand   https://mega.nz/#!KBVwVTZC!kacOuB2D03pG88M2aKAUXfMPbLNQZbkmxzEUR2o3OmQ

https://mega.nz/#!eI0gVJJb!GRTaxfLqOJvskMl8wezthnO2YKGDqnz8nD3GHngtbnw

**Comment by Keital** [comment]
@Tithand im cuban too where are you from?

**Comment by cooler-SAI** [comment]
I don't push on people, but if you join us - make few commits

**Comment by Tithand** [comment]
Thanks cooler-SAI i will donwload, Keital i from Matanzas

**Comment by Keital** [comment]
@Tithand check my profile dude

**Comment by cooler-SAI** [comment]
Ok, I deleted inactive people from repo write, who even doesn't make just 1 commit to repo. please, think before you wanna join us.
thanks to all

**Comment by Bodeguero** [comment]
@cooler-SAI You're doing it right because getting on the team doing nothing is better not to be on the team because all the staff are working on this source and dedicating to it!

Keep it boss :neckbeard:

Grateful 👊

**Comment by alexkulya** [comment]
Correct solution :+1:

**Comment by Keital** [comment]
Thumbs up!
