### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by alexkulya** [JadeCore/JadeCore#42]
At revert https://github.com/JadeEmu/JadeCore_547/commit/83e1febde26ef81a77667da667677b460efab395

Lost commits unrelated commit: mmaps.
Need restore.

**Comment by cooler-SAI** [comment]
mmaps was broken and Creature dosn't move in combat, so, that's why I revert Merge. If you loose any commit use Charry-pick, but I think I solved all usefull commits
