### ISSUE TITLE
Truice v1.3.8.2 Cataclysm could not search quest id! help !

### ISSUE THREAD

**Issue by cnmir2** [JadeCore/JadeCore#43]
Truice v1.3.8.2 Cataclysm could not search quest id! help !

hi cooler  want to use your uploaded Truice v1.3.8.2 Cataclysm to search some quest  but when i use  search the error occur :

sql error  unknown column "lq.id" on clause 

is this truice  is  not fit  for jadecore  database??

ty 
![qq 20161013075719](https://cloud.githubusercontent.com/assets/14962131/19332082/6a4cf14a-911b-11e6-88a2-b8866c5be250.png)

**Comment by cooler-SAI** [comment]
I use it for SAI fixes, creature's stats, spawns etc. may be Quest doesn't works, so, you need another tool I think
