### ISSUE TITLE
CMSG_REQUEST_HOTFIX: crash as unknown hotfix type: 4146370265

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#44]
kernel crash  at the end of the Server.log with the 5.4.8 branch  when  boat to the new world
ERROR CMSG_REQUEST_HOTFIX: Received unknown hotfix type: 4146370265

**Comment by Mysterium** [comment]
Which branch?

**Comment by SkyFire** [comment]
Packet order is incorrect.

**Comment by Keital** [comment]
@SkyFire we could use some help inhere if you're willing to, i could use some extra hands on mmaps, and from somebody with more knowledge like you hope you join us

**Comment by cooler-SAI** [comment]
@Keital , I added him to repo Writers, @SkyFire , hope you really can help us here. we all in the same boat

**Comment by Keital** [comment]
se no interest on him giving a hand :(

**Comment by SkyFire** [comment]
I would just null it out for now. You don't even have a handler for it yet.

**Comment by angelsss** [comment]
Which branch? -- 5.4.8
crash  When the boat to the new world, also crash when choise orc character 
I think the accident was due to a map

**Comment by angelsss** [comment]
Can someone help solve it

**Comment by Keital** [comment]
null opcode!!!

**Comment by angelsss** [comment]
Grateful

**Comment by zamalaev** [comment]
http://pastebin.ru/UrMpW0Vr

correctly?

**Comment by SkyFire** [comment]
Compile the core in release with debug. Post the crashdump in a pastebin.

**Comment by angelsss** [comment]
@zamalaev： yes ,the same error code
@SkyFire: ok , Is't to build -DWITH_COREDEBUG=1 ?  
I remember the gdb debug info : Floating point overflow ，and the detail to wait

**Comment by Bodeguero** [comment]
@angelsss Going to new world? As well? When you go to anywhere using the boat crash is that?
**Ex: Durotar to Borean**

This is how the this crash?

**Comment by angelsss** [comment]
@Bodeguero : yes , boat crash to anywhere
the  error info at the case of  -DWITH_COREDEBUG=0 :
=== gbd bt error info:  the crash dumpcore 2.8G ================================
Core was generated by `./worldserver-548'.
**Program terminated with signal 6, Aborted.**
**#0  0x00000033dda325e5** in raise () from /lib64/libc.so.6 (libc-2.12.so --centos)
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-42z1.el6_7.x86_64 libcom_err-1.41.12-22.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 openssl-1.0.1e-42.el6_7.4.x86_64 readline-6.0-4.el6.x86_64
(gdb) bt
#0  0x00000033dda325e5 in raise () from /lib64/libc.so.6
#1  0x00000033dda33dc5 in abort () from /lib64/libc.so.6
#2  0x00007fab8c4d707d in __gnu_cxx::__verbose_terminate_handler() () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fab8c4d50e6 in __cxxabiv1::__terminate(void (*)()) () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fab8c4d5131 in std::terminate() () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fab8c4d5348 in __cxa_throw () at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x00000000011d4ed0 in CreatureTextLocalizer<CreatureTextBuilder>::operator()(Player*) ()
#7  0x00000000011d90f1 in void CreatureTextMgr::SendChatPacket<CreatureTextBuilder>(WorldObject*, CreatureTextBuilder const&, ChatMsg, WorldObject const*, CreatureTextRange, Team, bool) const ()
#8  0x00000000011d2b0e in CreatureTextMgr::SendChat(Creature*, unsigned char, WorldObject const*, ChatMsg, Language, CreatureTextRange, unsigned int, Team, bool, Player*) ()
#9  0x00000000010073cd in CreatureAI::Talk(unsigned char, WorldObject const*) ()
#10 0x000000000163f75e in npc_vesperon::npc_vesperonAI::UpdateAI(unsigned int) ()
#11 0x0000000000cd9998 in Creature::Update(unsigned int) ()
#12 0x0000000000d782db in void Trinity::ObjectUpdater::Visit<Creature>(GridRefManager<Creature>&) ()
#13 0x0000000000e771c7 in Map::VisitNearbyCellsOf ()
#14 0x0000000000e77da5 in Map::Update(unsigned int) ()
#15 0x0000000000e77e30 in InstanceMap::Update(unsigned int) ()
#16 0x0000000000e6a724 in MapUpdateRequest::call() ()
#17 0x000000000121d462 in DelayExecutor::svc() ()
#18 0x00007fab8d0fdffd in ACE_Task_Base::svc_run(void*) () at Task.cpp:258
#19 0x00007fab8d0ff4d6 in ACE_Thread_Adapter::invoke_i() () at Thread_Adapter.cpp:159
#20 0x00007fab8d0ff3fd in ACE_Thread_Adapter::invoke() () at Thread_Adapter.cpp:94
#21 0x00000033fbe07aa1 in start_thread () from /lib64/libpthread.so.0
#22 0x00000033ddae8aad in clone () from /lib64/libc.so.6

**Comment by angelsss** [comment]
delay to solve it later
