### ISSUE TITLE
 Compile error

### ISSUE THREAD

**Issue by hero2880** [JadeCore/JadeCore#45]
win8.1;
vs2013.5_ce_enu;
Win64OpenSSL-1_0_2d;
mysql-5.6.27.0;
cmake-3.4.0
ACE 6.4.0.
source branch:548;(547 Compile sucessful )

ERROR LIST(Today's list did not keep, but the content is the same like the following):
Error	5	error C2047: illegal default	E:\download\JadeCore_547-JCDB548.07\src\server\game\Entities\AreaTrigger\Ar eaTrigger.cpp	389	1	game
Error	6	error C2043: illegal break	E:\download\JadeCore_547-JCDB548.07\src\server\game\Entities\AreaTrigger\Ar eaTrigger.cpp	390	1	game
Error	7	error C2059: syntax error : '}'	E:\download\JadeCore_547-JCDB548.07\src\server\game\Entities\AreaTrigger\Ar eaTrigger.cpp	392	1	game
Error	8	error C2143: syntax error : missing ';' before '}'	E:\download\JadeCore_547-JCDB548.07\src\server\game\Entities\AreaTrigger\Ar eaTrigger.cpp	392	1	game
Error	9	error C2143: syntax error : missing ';' before '{'	E:\download\JadeCore_547-JCDB548.07\src\server\game\Entities\AreaTrigger\Ar eaTrigger.cpp	395	1	game
Error	10	error C2447: '{' : missing function header (old-style formal list?)	E:\download\JadeCore_547-JCDB548.07\src\server\game\Entities\AreaTrigger\Ar eaTrigger.cpp	395	1	game
36	IntelliSense: a default label may only be used within a switch	e:\download\JadeCore_547-JCDB548.07\src\server\game\Entities
...

**Comment by Bodeguero** [comment]
From what I can see you are not doing right this mixed the source 5.4.7 and 5.4.8 at the same time as this error is not on 5.4.8!

Look:

CMake 3.4.3

http://image.prntscr.com/image/88027a191db0443b8e9ced392b641b33.jpg
http://image.prntscr.com/image/59a714a15d5844a385583f0773273070.jpg
http://image.prntscr.com/image/de98314a791343b78568d186ad411b16.jpg

Folder (Windows 10 Pro)

http://image.prntscr.com/image/fc693727b510435c8d042db59f63727e.jpg

Visual Basic 2013

http://image.prntscr.com/image/ee3ed3f7d7de4676b10ceed1319af800.jpg
http://image.prntscr.com/image/1d3b6a23e43b44f7ae2d2bfcd0e29985.jpg
http://image.prntscr.com/image/c9a9c4d29eb942c4b022ac4b9269a379.jpg
http://image.prntscr.com/image/6e8bd38f21e64555860bb0a3feb834c7.jpg
http://image.prntscr.com/image/24738529b97e4cf1bd0ef4940e31f7ea.jpg

**You could re-download the source and switch to brach 5.4.8 and try to compile again? Anything send me your contact via Skype.**

**Grateful!**

**Comment by hero2880** [comment]
the error list show "JadeCore_547-JCDB548.07" , in fact, I download the source code last nightand compiled this morning, but the error is same as list.
I will try again.

**Comment by Bodeguero** [comment]
@hero2880 **As I mentioned the sources are mixed so the error occurs again download and try to compile!**

**Gratful!**
