### ISSUE TITLE
mmaps for JadeCore

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#50]
Ok. guys. we need help here with mmaps.
We have branch "mmaps" tree, all discuss here. More people welcome.
https://github.com/JadeCore/JadeCore/tree/mmaps
All progress discuss with @Keital . So, keep open this issue. we need skilled people

**Comment by cooler-SAI** [comment]
may be it will be easy work with 5.4.8 mmaps ?

**Comment by Bodeguero** [comment]
@cooler-SAI I believe that 5.4.8 has the correct mmaps because I extracted them from the client and so far no errors!
I believe that 5.4.8 has the correct mmaps because I extracted them from the client and so far no errors!
We will check it? Another thing firm will work on 5.4.8 or 5.4.7 only in? What is your decision?

**Comment by cooler-SAI** [comment]
I think we must move to 5.4.8 and finished this Addon fully

**Comment by Bodeguero** [comment]
@cooler-SAI Well if you want you can test it, I leave it plugged into a host I have to test! He is now stable at the moment I am now looking for opcodes!

**Comment by cybrann** [comment]
I can start working on 5.4.8 soon.

**Comment by Keital** [comment]
port work to 5.4.8 and make it master branch, think thats the deal

**Comment by Bodeguero** [comment]
@Keital I fully agree with your decision!

**Comment by cooler-SAI** [comment]
Agree too, @Bodeguero , your turn)))

**Comment by Bodeguero** [comment]
Now default Branch 5.4.8 :neckbeard:

**Comment by wowharley** [comment]
Good choice 👍

**Comment by phulo** [comment]
nice

**Comment by Keital** [comment]
Closed as branch 5.4.8 already has mmaps. reopen if i'm wrong
