### ISSUE TITLE
World problem?

### ISSUE THREAD

**Issue by Krath** [JadeCore/JadeCore#51]
Hello everyone, I have successfully compiled the 5.4.8 branch , set up the DB and started the worldserver but it seems like I did something wrong. I cannot interact with any NPCs. I can't take quests, can't open gossip menus and such. I can't do anything. What did I do wrong?
Using your Wow.exe file and JCDB_548_07_full_2016_10_11 DB

**Comment by Bodeguero** [comment]
@Krath thanks for u report! Now Fixed!

**Comment by Krath** [comment]
No problem, it's always a pleasure to help with testing :)
