### ISSUE TITLE
crash in durotar

### ISSUE THREAD

**Issue by ro2016** [JadeCore/JadeCore#52]
if you go to durotar or start with orc the world server crashes in 5.4.8

**Comment by Bodeguero** [comment]
@hero2880 We are still moving, working on major things like classes, quests and then work in the Dungeons and Raids - it is logical that the branch 5.4.8 is less fixed than the branch 5.4.7 - I would like to look our summary of updates!

https://github.com/JadeCore/JadeCore/blob/5.4.8/TODO.md

Gratful!

**Comment by cnmir2** [comment]
Bodeguero why not merge the 548 and 547 together ? all fight for one  will be  not better?

**Comment by Bodeguero** [comment]
@cnmir2 It is what we are doing by adding the 5.4.7 fixes for 5.4.8 as mentioned above we are moving is not something so easy - if you wanted help us merge - send a PR doing it!

Grateful!

**Comment by cnmir2** [comment]
Bodeguero i am  newbie of c++ and i  want help but i didnt know how to learn fix something from scrach
but what ever  ty  very much for you  ,cooler  and your team hard work ! awesome!!

**Comment by cnmir2** [comment]
Bodeguero could you recommend  some book or video for learn c++for wow from scrach? ty

**Comment by ro2016** [comment]
ok i go try to solve this crash if can solve it i upload fix .if any  wants to see it only go to durotar on orcs start area
