### ISSUE TITLE
padaria raids

### ISSUE THREAD

**Issue by hero2880** [JadeCore/JadeCore#53]
Pandaria raids of 548 is bad than 547:Lightning Throne cannot enter;Orgrimmar battle no npcs;
Do not know if I did something wrong。

**Comment by Bodeguero** [comment]
@hero2880 We are still moving, working on major things like classes, quests and then work in the Dungeons and Raids - it is logical that the branch 5.4.8 is less fixed than the branch 5.4.7 - I would like to look our summary of updates!

https://github.com/JadeCore/JadeCore/blob/5.4.8/TODO.md

Gratful!

**Comment by hero2880** [comment]
Thank you for your patience.
