### ISSUE TITLE
Pandaren starting zone (cosmetics stuffs)

### ISSUE THREAD

**Issue by Cubansephiroth** [JadeCore/JadeCore#55]
The Pandaren Starting Zone (5.4.8) works much better than 5.4.7 branch("a lot better" phases now works very good)  .This is report guide of working quest and small things that can be improved. But in general the ZONE is PLAYABLE and you can get out of the island as intended.

Much to learn - Works
**The Lesson of the Iron Bough** - Works (tested with Pandaren Monk)
**The Lesson of the Sandy Fist** - Works (Some issues with LoS a bit with training target but quest can be completed)
**The Lesson of Stifled Pride** - Works  (Sometimes you stay in combat after killing trainees but can be completed)
**The Lesson of the Burning Scroll** - Works
**The Disciple's Challenge** - Works
**Items of Utmost Importance** - Works
**The Missing Driver** - Works
**The Way if the Tushui** - Works
**Ji of the Houjin** - Works
**The Way of Houjin** - Works
**Fanning the Flames** - Works
**Kindling the Fire** - Works
**The Spirit's Guardian** - Works
**The Challenger's fires** - Works
**Only the Worthy Shall Pass** - Autocompletable but working anyway..
**Hou the Spirit of Fire** - Works
**The Pasion of Shen-Zin Su** - Works (You should get a movement buff (Blessing of Huo - Spell=102630) from Hou but you can go anyway without speed)
**The Singing Pools** - Works
**Strongers Than Reeds** - Works
**The Lesson of Dry Fur** - Works (You didnt need to cross the balance poles but anyway is working)
**The Lesson of the Balanced Rock** -  Works (Balanced Poles are bugged if you jump into one you cant leave the pole neither jump to another one)
**Finding an old Friend** - Works
**The Sting of Learning** - Works
**The Sun Pearl - Works** (Autocomplete)
**Shu, The Spirit of Water** - Works
**A New Friend - Works** (Works Magically after few seconds)
**The Source of Livehood** - Works (Delivery Cart NPC id 57710) does not work you have to go by foot to Turn in the quest)
**Rascals** - Works
**Still Good!** - Works
**Missing Mallet** - Works
**Stronger Than Wood** - Works
**Raucous Rousing** - Works
**Not in the face** - Works
**The Spirit and Body of Shen-Zin Su** - Works (Delivery Cart NPC id 59497) does not work you have to go by foot to Turn in the quest)
**Morning Breeze Village** - Works(You got teleported to the upper part of the temple insted of being taken by the spell who raises you in the air but works anyway)
**Rewriten Wisdoms** - Works
**Tools of the Enemy** - Works
**Stronger than Stone** - Works
**The Direct Solution** - Works
**Do No Evil** - Works
**Monkey Advisory Warning** - Bugged (You can get the 8 Stolen Firework Bundles but cant Turn in the quest - maybe you need to abandon quest and take it again but didnt tested)
**Stronger Than Bone** - Works
	
Dafeng, the Spirit of Air (missing quest?)

**Battle for the Skies** -  Works ( Zhao-Ren is flying near ground with only 40hp and no Fireworks but if you kill him you get the credit and quest complete)
**Worthy of Passing** - Works
**Unwelcome Nature -** Works
**Small, But Significant** - Works
**Passing Wisdom** - Works
**The Suffering of Shen-Zin Su** - Works
**Bidden To Greatness** - Works
**Preying on the Predators** - Works
**Stocking Stalks** - Works but semi Bugged (You can get the 10 Broken Bamboo Stalks but cant Turn in the quest - You need to abandon the quest and take the quest again to be able to turn in)
**Wrecking the Wreck** - Works
**Handle with care** - Works
**Evil from the seas** - Works
**Urgent News** - Works
**None Left Behind** - Works
**Medical Supplies** - Works
**From bad to worse** - Works (when 7/8 DeepScale tormentor i killed the last one and counter reset to 1/8 but the second time works)
**An ancient Evil** - Works
**Risking it all** - Works
**The Healing of Shen-zin Su** - Works
**New Allies** - Works (Delivery Cart NPC id 57740) does not work you have to go by foot to Turn 
in the quest)
**A new Fate** - Half-Bugged (Missing the scene when you leave island by globe and you didnt take the credit when choose your faction so you cant turn in the quest in front of Orgrimmar Gates but anyway you can get out of the island and continue playing :) )

**Comment by Bodeguero** [comment]
@Cubansephiroth we are still working on the initial areas! If you can fix all help is welcome!

I worked a lot in these initial quests Pandaren!

Gratful!
