### ISSUE TITLE
Graveyard in Worgen Starting Zone?

### ISSUE THREAD

**Issue by Cubansephiroth** [JadeCore/JadeCore#58]
If you died in Worgen Starting Zone your spirit appear in Westfall :( you have to HS to get back to Gilneas.

**Comment by Bodeguero** [comment]
@Cubansephiroth We are still moving, working on major things like classes, quests and then work in the Dungeons and Raids - it is logical that the branch 5.4.8 is less fixed than the branch 5.4.7 - I would like to look our summary of updates!

https://github.com/JadeCore/JadeCore/blob/5.4.8/TODO.md

Gratful!
