### ISSUE TITLE
wowsource 5.4.8 VIP for public !!!

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#61]
WoWsource ( Ozeneu @Igorinus ) has been hacked by Anonymous. WoW 5.4.8 Source 2016 for Free! They want 500 euro for This! lol !!!

Here we go:
https://github.com/cooler-SAI/WS548-v4

**Comment by Bodeguero** [comment]
@cooler-SAI its version JadeCore 5.4.7 LoL

It just changes JadeCore for WoWSource!

https://github.com/cooler-SAI/WS548-v4/blob/master/src/server/authserver/Authentication/AuthCodes.h#L68
https://github.com/cooler-SAI/WS548-v4/blob/master/src/server/authserver/Authentication/AuthCodes.cpp#L24


https://github.com/JadeCore/JadeCore/blob/5.4.7/src/server/authserver/Authentication/AuthCodes.h#L68
https://github.com/JadeCore/JadeCore/blob/5.4.7/src/server/authserver/Authentication/AuthCodes.cpp#L24

**Comment by cybrann** [comment]
It's not jadecore, it's actually skymist core just a little bit combined with some other mop sources.

**Comment by Keital** [comment]
MMMMM i think Anonymous = Cooler-SAI, it's too much coincidence all leaks go to him lol

**Comment by Igorinus** [comment]
it is  just a disperate try to revive   attention and ofc this is a  old crap and  we have 4  diffrent cores for  protection and i can prove so enjoy this  old  core and think what ever  you wish hahahha
 

    On Monday, October 17, 2016 10:19 PM, Ander <notifications@github.com> wrote:
 

 WoWsource ( Ozeneu @Igorinus ) has been hacked by Anonymous. WoW 5.4.8 Source 2016 for Free! They want 500 euro for This! lol !!!Here we go:
https://github.com/cooler-SAI/WS548-v4—

**Comment by cooler-SAI** [comment]
Ok, I banned in ac-web ))))) lol

**Comment by alexkulya** [comment]
Ozeneu again robbed.

**Comment by Igorinus** [comment]
hahahah such a dreammer lol
 

    On Tuesday, October 18, 2016 7:16 AM, Alessandro Kulya <notifications@github.com> wrote:
 

 Ozeneu again robbed.—

**Comment by SkyFire** [comment]
Oh great. Another hacked together core source.

**Comment by Bodeguero** [comment]
Its old version

**Comment by cooler-SAI** [comment]
@Bodeguero  it's 2016 and for public))) we can use some things

**Comment by Remix99** [comment]
Can you please remove this RBAC system from your own 5.4.8 
really liked the 5.4.7 authserver system of jadecore with gmlevelo0 in account table etc but this 5.4.8 is totally different Zz

**Comment by Mysterium** [comment]
RBAC is shit.. no one want to use it

**Comment by Keital** [comment]
@cooler-SAI is this source's git history available somewhere??

**Comment by Igorinus** [comment]
people dont let your self  fullish by  some  kids  who post crap that posted  core its a  old crap the  real v4 is not even have rbac and  if you check teh  sql folder you will see how old it is and if are  still people  idiot enough to dont belive the owner which is me  i can  show you live the real source and  how it  looks like and  last thing  before i end this crap the real core  have  4  diffrent  version for  more protection against this  kind  of  toilet  shit  people  and  1  version is personal  only for me  the second  one is for  vip the third version is only for developers and  the  last version number  4  is   for new  team members  who dont prove  they are trusted and if you wish to see the real core  and the size etc  contact me in skype to geany_100 about  hack story  and so on crap its just a fairy tell story the github also can confirm in security option who was logged   in  history and  ip etc  and was just me and how i say meny times  i can prove  for  idiots who not belive so this core its a  old  shit v3 and the  shit   people who sare that just renamed  and  fullish people  like you with that fake name  i mean the one who really belive  hahahahha
 

    On Tuesday, October 18, 2016 6:45 PM, Adrian Rodriguez <notifications@github.com> wrote:
 

 @cooler-SAI is this source's git history available somewhere??—

**Comment by cooler-SAI** [comment]
@Keital , no, only source (

**Comment by Tithand** [comment]
i have a old version of wowsource 5.4.8 V4 (april 2016) (with full db) is it more recent?

**Comment by cooler-SAI** [comment]
@Tithand , Post DB please< I will update the source

**Comment by cooler-SAI** [comment]
Ok, Team, all you know where get this source. I close it
