### ISSUE TITLE
Repo Setup, hash revision not works!!!!!

### ISSUE THREAD

**Issue by Bodeguero** [JadeCore/JadeCore#63]
```
Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"
```

**Comment by SkyFire** [comment]
It's not that complicated.

**Comment by Bodeguero** [comment]
@SkyFire you could help or give us a hint of how to build with clang without giving errors to this source? For every time you compile with me clang of several errors only with gcc not error - the difference of them?

It might be possible to correct the above error?

Grateful!

**Comment by SkyFire** [comment]
Fixing right now.

**Comment by SkyFire** [comment]
Will finish after work.

**Comment by Bodeguero** [comment]
@SkyFire is not working :(((

Look:

https://travis-ci.org/JadeCore/JadeCore/builds/168591817

**Comment by Keital** [comment]
hahaha, @Bodeguero dont worry i will fix it, its not compicated just been working in my branch, later this night will do it promise

**Comment by Bodeguero** [comment]
@Keital  thanks Bro :)))

**Comment by angelsss** [comment]
the issue-- fatal: Couldn't find remote ref master
 when update local git source with command "git pull origin master"

**Comment by Keital** [comment]
remove ref to master branch manually in .git folder

**Comment by Keital** [comment]
remove ref to master branch manually in .git folder

**Comment by Keital** [comment]
remove ref to master branch manually in .git folder

**Comment by Keital** [comment]
remove ref to master branch manually in .git folder

**Comment by Keital** [comment]
remove ref to master branch manually in .git folder

**Comment by eXPeRi91** [comment]
https://github.com/JadeCore/JadeCore/pull/71 

Tested and working.

**Comment by SkyFire** [comment]
@Bodeguero Don't delete the init tag. It's needed for some reading the commit hash for some os's

**Comment by Bodeguero** [comment]
@SkyFire I'm sorry did not know!
