### ISSUE TITLE
JadeCore 4.3.4 Source For the Team

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#64]
Ok, guys. I added JadeCore Private  source to public ( it's improved wowsource + Ter-Server)
Best ever 4.3.4 source. I added all Team as writers, if someone wanna make some commits - free to go.
https://github.com/JadeCore/JadeCore/tree/4.3.4
added admins also XD

**Comment by Bodeguero** [comment]
@cooler-SAI i can add new branch 4.3.4?  Only for one repo!

Thanks for Shared

**Comment by Bodeguero** [comment]
@cooler-SAI Soon I will be providing the databases! Thanks for sharing this great source!

Gratful!

**Comment by cooler-SAI** [comment]
@Bodeguero , Ok! fixes welcome anytime))))

**Comment by wowharley** [comment]
@cooler-SAI or @Bodeguero can you accept my invite on skype, thanks

**Comment by wowharley** [comment]
@Mysterium are you able to add me on skype 
Skype: wowharley

**Comment by cooler-SAI** [comment]
@wowharley , added you! and please accept invite to the team https://github.com/JadeCore

**Comment by Keital** [comment]
@wowharley im cuban skype not available for my country it seems we are all TERRORISTS xD

**Comment by Dokman** [comment]
@Keital i am spanish and i am not a terorist and anyone that talk spanish is a terrorist, all the people is good people, terrorist are payed people

**Comment by Dokman** [comment]
@Keital No te ralles tanto, como diriamos los españoles.

**Comment by Keital** [comment]
@dokman lo de terroristas me refiero a los cubanos xD, google nos tiene bloqueados porque nuestro pais esta en la lista de paises que patrocinan el terrorismo segun los Estados Unidos, que para nada es cierto xD.
