### ISSUE TITLE
JadeCore 3.3.5 - what a source?

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#67]
@Bodeguero , what source do you use? TrinityCore or AzerothCore? I think last more playeble

https://github.com/azerothcore/azerothcore-wotlk

**Comment by Bodeguero** [comment]
@cooler-SAI at the moment I am using a trinitycore source with some my modifications this in my private project - will make the applications soon!

Gratfu!

**Comment by cooler-SAI** [comment]
@Bodeguero , ok, good news
