### ISSUE TITLE
Fix some startup error)

### ISSUE THREAD

**Issue by zamalaev** [JadeCore/JadeCore#73]
UPDATE `creature_template` SET `ScriptName` = "mob_orgrimmar_faithful" WHERE `entry`= 71715;
UPDATE `creature_template` SET `ScriptName` = "mob_orgrimmar_faithful" WHERE `entry`= 71774;
UPDATE `creature_template` SET `ScriptName` = "mob_korkron_ironblade" WHERE `entry`= 71516;
UPDATE `creature_template` SET `ScriptName` = "mob_korkron_arcweaver" WHERE `entry`= 71517;
UPDATE `creature_template` SET `ScriptName` = "mob_korkron_warshaman" WHERE `entry`= 71519;
UPDATE `creature_template` SET `ScriptName` = "mob_korkron_sniper" WHERE `entry`= 71656;
UPDATE `creature_template` SET `ScriptName` = "mob_korkron_banner" WHERE `entry`= 71626;

**Comment by Bodeguero** [comment]
@zamalaev this query is doing to correct that bug?

**Comment by zamalaev** [comment]
yes)

error DB
Script named 'mob_orgrimmar_faithful' does not have a script name assigned in database.
Script named 'mob_korkron_ironblade' does not have a script name assigned in database.
Script named 'mob_korkron_arcweaver' does not have a script name assigned in database.
Script named 'mob_korkron_assassin' does not have a script name assigned in database.
Script named 'mob_korkron_warshaman' does not have a script name assigned in database.
Script named 'mob_korkron_sniper' does not have a script name assigned in database.
Script named 'mob_aftershock' does not have a script name assigned in database.
Script named 'mob_korkron_banner' does not have a script name assigned in database.

ScripNamet
    new mob_orgrimmar_faithful();
    new mob_korkron_ironblade();
    new mob_korkron_arcweaver();
    new mob_korkron_assassin();
    new mob_korkron_warshaman();
    new mob_korkron_sniper();
    new mob_aftershock();
    new mob_korkron_banner();

**Comment by zamalaev** [comment]
а русские есть?))

**Comment by cybrann** [comment]
This is pretty useless because it only fixes db errors nothing else, general nazgrim script is not completely ported so it will not work anyway.

**Comment by Bodeguero** [comment]
@cybrann Ok, I removed the fix that! In:https://github.com/JadeCore/JadeCore/commit/d3dd3cfb6bcec934f54b0c2ac6fa2eea54472549

Gratfull!

**Comment by cybrann** [comment]
@zamalaev Do not post bugs about Kor'kron Dark Shamans or General Nazgrim that are not related to the in game spell or boss mechanics.

**Comment by cooler-SAI** [comment]
@zamalaev , есть русские)
