### ISSUE TITLE
Communication plattform

### ISSUE THREAD

**Issue by Keital** [JadeCore/JadeCore#77]
Guys this could be our comm plattform:
https://gitter.im/JadeCoreProject/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

give it a try

**Comment by Bodeguero** [comment]
@Keital nice job!

**Comment by Keital** [comment]
need some of the jadecore admins to create the integration links to github so it reports pulls request commits etc

**Comment by Mysterium** [comment]
Why no discord?

**Comment by cooler-SAI** [comment]
@Keital  and @SkyFire  promoted to Admins!
