### ISSUE TITLE
SQL update error: 2016_10_20_09_world_548.sql  with  Out of range

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#78]
Issue: the last sql at the end of **2016_10_20_09_world_548.sql** 

UPDATE creature SET equipment_id=0 WHERE equipment_id=69296;
ERROR: Out of range value for column 'equipment_id'  
 `equipment_id` tinyint(3) NOT NULL DEFAULT '0', （-32768 32767）

**the scheme of creature limit: equipment_id between  -32768 32767 but updated to 69296**

**Comment by Bodeguero** [comment]
@angelsss is using this version? https://github.com/JadeCore/JadeCore/releases/tag/JCDB548.07?

I just download this release and runs the query and I have no errors! Very strange it!

I'm using **JCDB_548_07_full_2016_10_11.sql** - no have errors look:

**1 queries executed, 1 success, 0 errors, 0 warnings**

```
Query: UPDATE creature SET equipment_id=0 WHERE equipment_id=69296

1 row(s) affected

Execution Time : 0.050 sec
Transfer Time  : 0 sec
Total Time     : 0.051 sec
```

**Comment by Ruundok** [comment]
confirm, no errors with this sql update, works fine (with Navicat).

**Comment by phulo** [comment]
solved

**Comment by angelsss** [comment]
@Bodeguero  yes to use sql file :  JCDB_548_07_full_2016_10_11.sql  
never mind: I try to fix  ,perhaps as mysql5.7

**Comment by Bodeguero** [comment]
@angelsss reinstall your MySql server and use Navicat to give Dump!
All tested us and we have no mistake - this must be because someone program your bad installed or even buggy!

Grateful!
