### ISSUE TITLE
Mists of Pandaria Dungeon bugs list?

### ISSUE THREAD

**Issue by cybrann** [JadeCore/JadeCore#79]
Does anyone have dungeons bug list from the 5.4.8 branch? I mean like all expansion bugs from 5.4.8 branch?

**Comment by Bodeguero** [comment]
@cybrann Well I believe that no one has this so complete list - which I tested I reported in TODO.md file - now a full list think anyone has it!

🤕

**Comment by cybrann** [comment]
Ah I'll just rewrite every dungeon completely.

**Comment by Bodeguero** [comment]
@cybrann I have a Host for testing only if you want I can call it for you to do the necessary tests!

**Comment by cybrann** [comment]
I can test it on my own pc, but I'm guessing all of them are not working fully so it will be better to rewrite.

**Comment by Bodeguero** [comment]
@cybrann I totally agree, I am now seeing the issue of enchantment items! 🤓

**Comment by cybrann** [comment]
If you fix enchanting it would be great :D

**Comment by cooler-SAI** [comment]
@cybrann  very impressive job in Dungeons and Raids!
