### ISSUE TITLE
Extract Maps error:  from client wow548 with built-bin file such as mapextractor,vmap4extractor 

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#81]
The lacking Maps perhaps emerged crash:
e.g1:  mapextractor error info:
 No such file World\Maps\Transport_Siege_of_Orgrimmar_Hord\Transport_Siege_of_Orgrimmar_Horde.wdt

e.g2:  vmap4extractor  error info: 
Can't open World\Maps\MistsCTF3\MistsCTF3.wdt, err=2!
Extracting GameObject models...Fatal error: Invalid GameObjectDisplayInfo.dbc file format!

**Comment by zamalaev** [comment]
NO

**Comment by zamalaev** [comment]
https://github.com/zamalaev/CustomJadeCore/releases

**Comment by angelsss** [comment]
thanks ,I  will try
