### ISSUE TITLE
Start DB ERROR:  1648 of quests can't be done 

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#82]
Error info in DBErrors.log  when staring ,but few error before--( occur at version ea7e0f8 )
e.g: 
Quest 31760 has `RewardCurrencyId2` = 396 but `RewardCurrencyCount2` = 0, quest can't be done.
Quest 31760 has `RewardCurrencyId3` = 738 but `RewardCurrencyCount3` = 0, quest can't be done.

**Comment by cooler-SAI** [comment]
What branch do you use? looks like it's old 5.4.7 Errors. I don't see it in 5.4.8. Can't accept this report

**Comment by Bodeguero** [comment]
@angelsss When sending u /report bugs/errors put which branch is!
Grateful!

**Comment by cybrann** [comment]
@Bodeguero Only put which platform it is when crash or compile error is reported.

**Comment by Bodeguero** [comment]
@cybrann 🤓
