### ISSUE TITLE
5.4.7 > 5.4.8

### ISSUE THREAD

**Issue by augy21** [JadeCore/JadeCore#83]
Last month i have been using 5.4.7 on LAN and was making a list of broken quests to add for jadecore.

Notice you guys switched to 5.4.8 but i have found no update to convert over to 5.4.8.

Wondering if you guys can still post the SQL update to convert Auth and Character database from 5.4.7 to 5.4.8 or would i have to start over again?

**Comment by cybrann** [comment]
It's a completely different core we used as a base for 5.4.8 so, yes you need to start over everything. 5.4.7 was very hacky so everything will be rewritten before adding it to 5.4.8.

**Comment by augy21** [comment]
Ok thank you.
