### ISSUE TITLE
originall Private VIP WoWSource Cataclysm 4.3.4 Repo 2016 for all

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#84]
It's originall Private VIP WoWSource Cataclysm 4.3.4 Repo 2016 for all. Thanks to Anonymous for the Hack http://wowsource.info/ AGAIN! ))))))))
We have all of their Source for now! xD

https://github.com/cooler-SAI/WoWSource434

**Comment by Mysterium** [comment]
Anonymous again? you ARE anonymous! :laughing:

**Comment by cooler-SAI** [comment]
@Mysterium , tsssss, quet.. be quet 💃 💃 💃

**Comment by alexkulya** [comment]
Hackers have started to operate. I'm starting to worry :)

**Comment by Bodeguero** [comment]
@cooler-SAI It is better than our source or not Cooler?

**Comment by cooler-SAI** [comment]
Need Test,can someone help me testing?
