### ISSUE TITLE
[4.3.4] many bugs of all cata raids

### ISSUE THREAD

**Issue by sunshitwowsucks** [JadeCore/JadeCore#85]
there are many bugs of all cata raids and all dungs need new sniffs and need be rewritten. also problem in raid if you do boss on 10 man and switch to a diff mode ( i tested 25 man hc) everything respawns even if u have id, also hp is bugged on 99% of thrash/bosses and not correct

**Comment by cooler-SAI** [comment]
Need check wowsource VIP version. We can use their source,can you test it?

**Comment by sunshitwowsucks** [comment]
i think it is same, i will test in morning

**Comment by cooler-SAI** [comment]
@sunshitwowsucks , no! hackers get only source ((((

**Comment by cooler-SAI** [comment]
OMG!! I forgot about config!))))))
```sql
Rate.Creature.Normal.Damage          = 1
Rate.Creature.Elite.Elite.Damage     = 0.2
Rate.Creature.Elite.RARE.Damage      = 0.2
Rate.Creature.Elite.RAREELITE.Damage = 0.2
Rate.Creature.Elite.WORLDBOSS.Damage = 0.2
```

lol!))))))))))))))))
