### ISSUE TITLE
Base Source 4.3.4 for JadeCore

### ISSUE THREAD

**Issue by cooler-SAI** [JadeCore/JadeCore#88]
Ok, guys! I think we must use last wowsource as base for our 4.3.4, coz they have improoved C++ and many Quests fixes in Database.. I will upload last full DB with all updates to wowsource and we can use it.
@Bodeguero , pleaseset Travic for this source https://github.com/cooler-SAI/WoWSource434
please don't change icons and folders ( include Not Finished folder)

**Comment by Keital** [comment]
Write access??

**Comment by Bodeguero** [comment]
@cooler-SAI ok Boss

**Comment by cooler-SAI** [comment]
@Keital , wewill add allto JadeCore 4.3.4

**Comment by Keital** [comment]
ok have to look at code hope it's not that old

**Comment by cooler-SAI** [comment]
Ok, @Bodeguero , we ready for Port Sources, I added Databases! they already include last "patch" SmartAI and all updates!
https://github.com/cooler-SAI/WoWSource434

**Comment by Keital** [comment]
it's wowsource 434 better than TC 434??? why not use TC 434 as base??

**Comment by sunshitwowsucks** [comment]
tc 434 need lot of work, but would be better to use it as base

btw this vip core not a lot different than current one still have many same bug i think only some quest are fix in this one

**Comment by cooler-SAI** [comment]
TC need a loooot of work,dungeons,raids,zones phases not scripted.wowsource more improoved here,not all blizzlike but it works

**Comment by Keital** [comment]
yea but its easier port spawns and instances to tc than implementing in wowsource all good things that TC already has, boost mmaps dbupdater etc, just my opinion

**Comment by cooler-SAI** [comment]
There are many work in TC,no one will do it huge work,better focus on 5.4.8 and make little fixes for 4.3.4

**Comment by Dokman** [comment]
@cooler-SAI @Keital @Bodeguero Arkania is doing a lot of things, just only two guys... so... you are 3 or 4 you can do it more things, but you will have to learn the code and learn how to make good scripts with the sniffs
i don't have time, but when i can i will do it, it will be a good playground to practice my c++ and my logic

**Comment by cooler-SAI** [comment]
ok, guys! i am ready for make fixes in 4.3.4, after source will be ported to our JadeCore 4.3.4 repo.
@Bodeguero , how soon we can start work?

**Comment by Flameshot** [comment]
@cooler-SAI  hello man. My best advice for you is don't use wowsource. I worked there I know perfectly their source is full of hack fixes and crashes... duplicates and shitty database fixes. If you want to do something nice add trinitycore 4.3.4 https://gitlab.com/trinitycore/TrinityCore_434 . I can add some fixes too. Trinitycore doesn't have so much fixes but their are very stable.

**Comment by Bodeguero** [comment]
@cooler-SAI Soon start to work on it, give me 03 days to move the corrections to our branch 4.3.4!

Grateful!

**Comment by sunshitwowsucks** [comment]
@cooler-SAI we should use https://gitlab.com/trinitycore/TrinityCore_434 and i can start work on fixing dungs/raids/spells it will be better base and easier to work on

**Comment by Flameshot** [comment]
@sunshitwowsucks  hello :) . I can help you guys too.

**Comment by cooler-SAI** [comment]
ok, I seemany people vote for 4.3.4 TrinityCore. Only 1 thing - we must use merges from Official Trinity Repo https://gitlab.com/trinitycore/TrinityCore_434/commits/4.3.4
So, @Bodeguero , use TrinityCore 4.3.4 source, If people like it more better

**Comment by cybrann** [comment]
I vote for TrinityCore too as cata source. I will most likely do cata dungeons/raids for 5.4.8 and port them to 4.3.4.

**Comment by cooler-SAI** [comment]
ok, @sunshitwowsucks, @Flameshot , added you! you can start make fixes. all team added also
https://github.com/JadeCore/TrinityCore/invitations

source
https://github.com/JadeCore/TrinityCore

**Comment by Flameshot** [comment]
@cooler-SAI  the bad thing about making fork is that I cannot use the search but it is ok

**Comment by Dokman** [comment]
i vote for a 4.3.4 from TrintyCore is too much better and then we can work with a good base

**Comment by Flameshot** [comment]
@Dokman  the source was already made

**Comment by Keital** [comment]
kay guys welcome @sunshitwowsucks @Flameshot glad you join us, closing this as a decision was made :smile:

**Comment by sunshitwowsucks** [comment]
we need issue tracker for this branch, possible to not use fork?

**Comment by cooler-SAI** [comment]
@sunshitwowsucks , sure! let me see.....

**Comment by cooler-SAI** [comment]
@sunshitwowsucks , I added issue for fork

**Comment by cooler-SAI** [comment]
P>S> new Coders! also visit https://github.com/JadeCore to accept the invitation

**Comment by sunshitwowsucks** [comment]
ty
