### ISSUE TITLE
[5.4.8] build issue: now need boost ?

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#91]
﻿[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
[5.4.8] build issue: now need boost  ?

**Current behaviour:** (Tell us what happens.)
build error as need boost ,but not need before ,exactly add boost ?

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1.  start build
2. 
3. 

**Branch(es):** 5.4.8 / 4.3.4 / 3.3.5 (Also add Labels to identify Information)
5.4.8
**JadeCore rev. hash/commit:**   b606c0d

**JCDB version:**   JCDB_548_07_full_2016_10_11.sql  (now)

**Operating system:**  linux

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keital** [comment]
yes now core requires boost, things to come will use it
