### ISSUE TITLE
[5.4.8] Crash signal 11: Segmentation fault as boss_lorewalker_stoneste.cpp

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#92]
﻿[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
gdb crash debugcore error:
Core was generated by `./worldserver-548'.
Program terminated with signal 11, Segmentation fault.
#0  boss_lorewalker_stonestep::boss_lorewalker_stonestep_AI::MoveInLineOfSight(Unit*) ()
    at JadeCore/src/server/scripts/Pandaria/Dungeons/TempleoftheJadeSerpent/boss_lorewalker_stonestep.cpp:184
184                                     instance->SetData(TYPE_LOREWALKTER_STONESTEP, 1);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-42z1.el6_7.x86_64 libcom_err-1.41.12-22.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 openssl-1.0.1e-42.el6_7.4.x86_64 readline-6.0-4.el6.x86_64
(gdb) bt
#0  boss_lorewalker_stonestep::boss_lorewalker_stonestep_AI::MoveInLineOfSight(Unit*) ()
    at JadeCore/src/server/scripts/Pandaria/Dungeons/TempleoftheJadeSerpent/boss_lorewalker_stonestep.cpp:184
#1  0x0000000001018c22 in CreatureAI::MoveInLineOfSight_Safe(Unit*) () at JadeCore/src/server/game/AI/CreatureAI.cpp:127
#2  0x0000000000d7e466 in Trinity::PlayerRelocationNotifier::Visit(GridRefManager<Creature>&) ()
    at JadeCore/src/server/game/Grids/Notifiers/GridNotifiers.cpp:134
#3  0x0000000000d805d1 in Trinity::DelayedUnitRelocation::Visit(GridRefManager<Player>&) ()
    at JadeCore/src/server/shared/Dynamic/TypeContainerVisitor.h:59
#4  0x0000000000e85dc4 in Map::ProcessRelocationNotifies(unsigned int) ()
    at JadeCore/src/server/shared/Dynamic/TypeContainerVisitor.h:59
#5  0x0000000000e861ab in Map::Update(unsigned int) () at JadeCore/src/server/game/Maps/Map.cpp:677
#6  0x0000000000e86290 in InstanceMap::Update(unsigned int) () at JadeCore/src/server/game/Maps/Map.cpp:2827
#7  0x0000000000e775e4 in MapUpdateRequest::call() () at JadeCore/src/server/game/Maps/MapUpdater.cpp:44
#8  0x000000000123fc02 in DelayExecutor::svc() () at JadeCore/src/server/shared/Threading/DelayExecutor.cpp:67
#9  0x00007faefc98fffd in ACE_Task_Base::svc_run(void*) () at Task.cpp:258
#10 0x00007faefc9914d6 in ACE_Thread_Adapter::invoke_i() () at Thread_Adapter.cpp:159
#11 0x00007faefc9913fd in ACE_Thread_Adapter::invoke() () at Thread_Adapter.cpp:94
#12 0x00000033fbe07aa1 in start_thread () from /lib64/libpthread.so.0
#13 0x00000033ddae8aad in clone () from /lib64/libc.so.6

**Current behaviour:** (Tell us what happens.)
crash when battle to boss lorewalker

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1.  to battle to boss 
2. 
3. 

**Branch(es):** 5.4.8 / 4.3.4 / 3.3.5 (Also add Labels to identify Information)

**JadeCore rev. hash/commit:**   a014d1446775

**JCDB version:**  JCDB 548.07

**Operating system:**  linux

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Bodeguero** [comment]
@angelsss Add the labels too! Add the labels too (Also add Labels to identify Information)! Or shut your Issue!
