### ISSUE TITLE
[5.4.8] Start DB ERROR: 1648 of  "quest can't be done"

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#93]
﻿[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
[5.4.8] Start DB ERROR: 1648 of  "quest can't be done" at DBErrors.log
Is't normal ?
---------
Error such as : 
Quest 33235 has `RewardCurrencyId2` = 777 but `RewardCurrencyCount2` = 0, quest can't be done.
Quest 32603 has `RewardCurrencyId2` = 396 but `RewardCurrencyCount2` = 0, quest can't be done.

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1.  start 5.4.8 use newest version and JCDB 
2. 
3. 

**Branch(es):** 5.4.8 / 4.3.4 / 3.3.5 (Also add Labels to identify Information)
5.4.8

**JadeCore rev. hash/commit:**  bc03ca082e8c 

**JCDB version:**  548.08

**Operating system:**  linux

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Bodeguero** [comment]
@angelsss Add the labels too! Add the labels too (Also add Labels to identify Information)! Or shut your Issue!
