### ISSUE TITLE
[5.4.8] how to add the labels can you  teach me

### ISSUE THREAD

**Issue by angelsss** [JadeCore/JadeCore#95]
#﻿[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

few issue closed by needed add the lables,but I don't know to how add,
 Can you teach me ? I have no privilege

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 

- 

- [ ] 1. 

3. 

**Branch(es):** 5.4.8 / 4.3.4 (Also add Labels to identify Information)

**JadeCore rev. hash/commit:**  

**JCDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by cybrann** [comment]
Idk why close fhem, only developers of the project should add labels
