### ISSUE TITLE
Instance Mobs

### ISSUE THREAD

**Issue by avatar789** [JadeCore/JadeCore#96]
Nope not one mob in instances \ raids Pandaria

**Comment by wowharley** [comment]
Can you name the instance that don't have spawns ?

**Comment by avatar789** [comment]
Sige of Orgrimmar, Mogushan, 
http://screenshot.ru/upload/images/2016/10/25/WoWScrnShot_102516_224736b3830.jpg
http://screenshot.ru/upload/images/2016/10/25/WoWScrnShot_102516_2248373ffd8.jpg
The rest have not yet come in, in the two caves there are no mobs
Sorry my English

**Comment by cybrann** [comment]
I already wrote about this issue with team on skype few days ago

**Comment by hero2880** [comment]
Error same as me,almost all  instances and raids of Pandaria.

**Comment by hero2880** [comment]
548's raids no npcs spwan too....(pangushavault is ok);   complied 20min ago
[http://i1.piimg.com/577587/ddf590db1f1fc7f1t.jpg](url)
[http://i1.piimg.com/577587/9e13572c6fe76075t.jpg](url)
