### ISSUE TITLE
Portal of the isle of thunder

### ISSUE THREAD

**Issue by karly911118** [JadeCore/JadeCore#97]
﻿[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 5.4.8 / 4.3.4 (Also add Labels to identify Information)

**JadeCore rev. hash/commit:**  

**JCDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by cybrann** [comment]
Closing invalid report.
