### ISSUE TITLE
cooler-SAI

### ISSUE THREAD

**Issue by zamalaev** [JadeCore/JadeCore#99]
это адресованно тебе так как с английским с наречиями беда))) Предлогаю заняться легионом с моего форка я реализую ПвП систему в ближающую неделю нужна огромна, очень большая работа с БД, ч знаю ты можешь это сделать

**Comment by zamalaev** [comment]
меня интересует просто актуальная версия wow и может завалялось либо есть снифф http://ru.wowhead.com/tarren-mill-vs-southshore все готово надо ток объекты глянуть)) бафы и механику БГ, но написанно хаком под тип http://ru.wowhead.com/eye-of-the-storm

**Comment by cooler-SAI** [comment]
нету времени и желания
